name: PR Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --all-features --release

  licenses:
    name: file licenses
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install ripgrep
        # https://github.com/BurntSushi/ripgrep/releases
        env:
          ripgrep_version: 14.1.1
        run: |
          wget https://github.com/BurntSushi/ripgrep/releases/download/${{ env.ripgrep_version }}/ripgrep_${{ env.ripgrep_version }}-1_amd64.deb
          sudo dpkg -i ripgrep_${{ env.ripgrep_version }}-1_amd64.deb
          rg --version || exit 1

      - name: run the license check
        run: ./scripts/file_license_check.sh
