name: PR Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

      - name: Lint
        run: |
          echo "$PR_TITLE" | commitlint
        env:
          PR_TITLE: ${{github.event.pull_request.title}}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: sudo apt install libdbus-1-dev pkg-config

      - name: Install cargo-machete
        run: |
          cargo install cargo-machete

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run cargo test
        run: |
          cargo test --locked --all-features --release
          # cargo nextest run --all-features --release --profile ci

      - name: Run cargo machete
        run: cargo machete
